name: ci

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: set up buildx
        uses: docker/setup-buildx-action@v3

      - name: login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          tags: |
            ghcr.io/${{ github.repository_owner }}/kubeops:latest
            ghcr.io/${{ github.repository_owner }}/kubeops:commit-${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          context: .
          push: ${{ github.event_name == 'push' }}
